### ISSUE TITLE
Problem with resetting games while frame limiter is off in the DirectSound plugin

### ISSUE THREAD

**Issue by LegendOfDragoon** [Azimer/AziAudio#127] opened 2015-10-05 02:07 UTC
When I reset a game in Project64 2.2 with frame limiter off, it sometimes repeatedly plays the sound that's currently in the buffer forever. Does not happen with the XA2 plugin.

**Comment by Frank-74** [comment] 2015-10-07 00:33
Also F2 Pause in PJ2.2, sometimes continues playing what's in the buffer before pausing.  Might be related to having a random delay in video/audio sync with DS8.

**Comment by LegendOfDragoon** [comment] 2015-10-07 00:51
>Also F2 Pause in PJ2.2, sometimes continues playing what's in the buffer before pausing. Might be related to having a random delay in video/audio sync with DS8.

What you described simply means there was a lot in the buffer (typically happens in FAT or when you play at > 60 VI/s). The problem I mentioned has to do with an initialization / deinitialization issue.

**Comment by LegendOfDragoon** [comment] 2015-10-30 20:38
@Frank-74 I tried latest source and it still has the issue.

**Comment by Frank-74** [comment] 2015-11-01 13:21
@LegendOfDragoon 
Hmmm...  I tested with Goldeneye after adding the StopAudio to Reset, and it fixed it here.  Before I had sound repeating forever after reset with frame limiter off.

Maybe I was also using your GetReadStatus experiment?

**Comment by LegendOfDragoon** [comment] 2015-11-01 20:06
@Frank-74 I think it has more to do with the fact that the infinite repeating noise doesn't always occur. Sometimes it takes me a few tries.

**Comment by Frank-74** [comment] 2015-11-04 22:33
@LegendOfDragoon 
I cannot reproduce it all.  The only other difference I can think of is I use CN64System Time Critical setting, which also lowers the audio thread to Highest priority.  DX DSound always runs at Time Critical, regardless of what the audio thread is set at.

**Comment by Frank-74** [comment] 2017-02-07 22:27
@LegendOfDragoon 
Is this still an issue on your side with the current source?

I reset Goldeneye a dozen times with frame limiter off.  Also hammered savestate and loadstate repeatedly with frame limiter off.  It seems fine now.

**Comment by LegendOfDragoon** [comment] 2017-02-08 00:06
@Frank-74 yea it's still an issue on my end. I tried the build you linked in that pull request. Try Super Smash Bros.

**Comment by Frank-74** [comment] 2017-02-08 01:01
Yes, SSB repeats the last buffer sound endlessly.  DS8 mustn't be flushing the buffers/DMA whatever it uses.  XA2 is fine.

**Comment by Azimer** [comment] 2017-02-28 19:02
This should be fixed.

**Closed** 2017-03-07 20:50 UTC
Labels: bug, fixed
