### ISSUE TITLE
Losing sound switching plugins (again)

### ISSUE THREAD

**Issue by Frank-74** [Azimer/AziAudio#188] opened 2017-03-03 00:41 UTC
With new build, switching from AziAudio to Jabo back to AziAudio, and sound is gone.

I tested with SND_DRIVER_XA2 and SND_DRIVER_XA2L.

Incidentally, XA2L sounds much better for TWINE than XA2.  New XA2, music stutters badly.

The snd->AI_ResetAudio() in RomOpen, is the cause of losing audio.
https://github.com/Azimer/AziAudio/blob/master/AziAudio/main.cpp#L222

**Comment by Azimer** [comment] 2017-03-05 05:14
Thanks for the feedback. I will look once I am back from a personal trip.

**Comment by Azimer** [comment] 2017-03-07 20:36
This issue was AiDacrateChange was being issued before RomOpened (and the Reset).  I moved the reset to RomClosed, ran a few tests successfully.  Hopefully this will fix the problem and not cause any regressions.

**Comment by Azimer** [comment] 2017-03-07 20:39
As far as TWINE stuttering goes...  I am not experiencing the same issue.  Is there an open issue related?

**Comment by Frank-74** [comment] 2017-03-07 21:29
Losing sound switching plugins is fixed.

Example of TWINE stuttering on my end.  It only happens with new audio code.  Legacy is ok.
Recordings are bad, they don't sound bad when playing, but recording on this laptop is very bad.
https://www.dropbox.com/s/t1ub165hcn4mwlf/TWINE_XA2.mp3?dl=1
https://www.dropbox.com/s/29p65eknocmgctx/TWINE_XA2L.mp3?dl=1

**Comment by Azimer** [comment] 2017-03-07 21:57
Sounds like your laptop isn't keeping up with the audio demands.  Can I get your specs and number of cpu cores?  OS? etc.  This isn't a "your laptop is an issue" comment...  more of a "I dev on an overclocked 6700k" type comment.  I don't experience the same potential processing issues.

**Comment by Frank-74** [comment] 2017-03-07 22:37
Intel Pentium N3540 @ 2.16Ghz, quad core.
4Gb Ram.
Windows 8.1 64-bit.
Realtek High Definition Audio.
Intel HD Graphics, supports upto GL4.0.

**Comment by Azimer** [comment] 2017-03-07 22:52
You might have some luck modifying https://github.com/Azimer/AziAudio/blob/master/AziAudio/XAudio2SoundDriver.cpp#L195.
https://github.com/Azimer/AziAudio/blob/master/AziAudio/SoundDriver.cpp#L73

/90 is what I had to use for EmulateAI to get it to trigger MusyX games often enough.  The audio frame rate is ~120 fps.  So 90 was a good estimate for my machine without causing issues.  You may be able to modify the above and get some success.  The constant 90 is 90 fps.  So try 60 or 30 with FAT.  This will also increase latency slightly but be less CPU dependent.

**Comment by Frank-74** [comment] 2017-03-07 23:34
I tried 60 and 40, was improved, but still stuttered.  So changed the maxbuffer to *4, in SoundDriver.cpp and it's ok, left it at /90.

```cpp
	m_MaxBufferSize = (u32)((Frequency / 90)) * 4 * 4; // TODO: Make this configurable
```

**Comment by Frank-74** [comment] 2017-03-08 01:41
One other bug, cannot start a second game with DS8.  End emulation, restart game, PJ64 crashes.  XA2 is ok.

**Comment by Azimer** [comment] 2017-03-08 01:55
Did it work prior to this last commit? 


-------- Original message --------

**Comment by Frank-74** [comment] 2017-03-08 02:21
> Did it work prior to this last commit?

I don't know, tonight is first time I built DS8 version since before new audiocode 181.  It was ok then.

**Comment by Azimer** [comment] 2017-03-08 02:58
Thanks for all this information.  It's really valuable.  I will see what I can try.  
If you right click on the speaker icon, go to playback devices, right click your default output device and click properties.  What does it say for playback format and exclusive mode?

**Comment by Frank-74** [comment] 2017-03-08 03:04
![audiooptions](https://cloud.githubusercontent.com/assets/11056843/23688349/f524fc74-03ab-11e7-92d2-ce0c78c1fcd3.JPG)

**Comment by Azimer** [comment] 2017-03-08 04:04
No.  I think keeping it at your default is fine....  I had no idea there was such an effect.  I think it's related though... a resampling issue because of the extra computation.

**Comment by Frank-74** [comment] 2017-03-08 04:43
I just tested using 16 bit 48000 playback in my audio settings.  I changed back to freq / 90 * 4 * 2 in SoundDriver.cpp.  I'd already changed every instance of 44100 to 48000, so left it at that.
It sounds mostly ok now, with PBO on, minor stutters.  But it's still better with a bigger maxbuffersize.

**Comment by Azimer** [comment] 2017-03-08 04:50
Now to see how I can take this information and use it wisely.

**Comment by Azimer** [comment] 2017-03-08 19:19
From my understand after looking into the issue.  XAudio2 will default the mastering voice to the speaker setup on your computer.  The source voice is setup as 44100 by the plugin but will change that frequency to whatever the game frequency is.  I am finding this curious.

**Comment by Azimer** [comment] 2017-03-08 19:26
https://github.com/Azimer/AziAudio/commit/ed0566c290877f2473ec3baad1f12f0fe9b57d53 created to help test.

**Comment by Azimer** [comment] 2017-03-09 01:12
> One other bug, cannot start a second game with DS8. End emulation, restart game, PJ64 crashes. XA2 is ok.

This isn't happening for me.  I started one image.  Got some audio.  End Emulation.  Start Emulation.  No issue.  End Emulation.  Opened a new rom.  Got some audio.  End Emulation.  Start Emulation.  No crashes.

What version of Project64 are you using?  I think I am using https://github.com/project64/project64/commit/6d8933674d0bc590a946676e316230e06665fee5

**Comment by Frank-74** [comment] 2017-03-09 08:06
>  The source voice is setup as 44100 by the plugin but will change that frequency to whatever the game frequency is. I am finding this curious.

I found when debugging PJ64's audio about a year ago.  That 44100 game frequencies were actually greater or less than 44100, never exactly 44100, unless you fiddle with the CPU speed in the VI/dacrate calculation.  At the time, someone made a rounding function to force the game frequencies to 44100 32000 22050 etc.  But it made the audio stutter.  I did find a CPU speed that got exactly 44100 22050 32000 16000 etc without rounding and it sounded ok.  I'd have to experiment again to find it again.

Higher output sample rate also means lower latency.  Because the audio chunks are smaller.  From my days when I did lots of audio multitrack recording with cakewalk and cubase etc.  I used to record at 96000 with a latency of 10ms, when I had a good soundcard/hardware (M-Audio Delta 1010).  If I set the sample rate to 44100, latency was much larger, attempting to use lower latency (small buffer) resulted in crackling.

Also, with my sound set to 24bit, and the maxbuffersize at freq / 90 * 4 * 2, it's very bad stutter.  Setting to 16bit and it's much better.

> What version of Project64 are you using?

https://github.com/Frank-74/project64/tree/Revert-%23984
I reverted a commit to optimize timers, as it caused stuttering in TWINE with register caching enabled.
I also removed the hacks made for Jabo's plugins, that made another thread because of a bug.  Apparently the bug was pre Jabo's 1.5.2, because neither 1.5.2/1.6 or 1.7 plugins have the bug, but the hacks were still there.  They affect all win32 plugins, not just jabo though.

**Comment by Frank-74** [comment] 2017-03-09 09:42
Regarding the DS8 crashing.  I get the crash when end emulation, and double click the game in the ROM browser to restart.  One time, I pressed cancel on the crash dialog, and the game started instead of PJ64 closing, then I was able to end/start without further crashes.  One oddity I just found, if I use the menu option 'start emulation', it restarts from where it ended, as if it's restarting from a savestate, and doesn't crash.  Very odd.  I suspect a problem with PJ64.

**Comment by Azimer** [comment] 2017-03-09 14:06
I tried your DS8 steps again with the build I am using.  No issues.  I suspect it may be more of a plugin issue other than audio?  I am using Jabo's Direct3D8 1.7.0.57-ver 5.  Azimer's Audio (whichever I am working on in development).  N-Rage for PJ64 (Debug) 2.5.2.9999.  RSP Plugin 1.7.0.9. for testing.
>  Setting to 16bit and it's much better. Is there a way AziAudio could force 16bit output?
It's already forced to 16bit for the source voice.  The way it works is source voice -> mastering voice -> system.  source voice to mastering does a conversion from your sample/bit rate to whatever the mastering voice is setup as (which is system default).  From there it sends the data to the hardware layer windows uses to integrate everything (probably a WASAPI wrapper does this).  So if we play at 44100/16bit it will be translated to 48000/24bit.  Which will in turn be translated 1:1 by this layer (no work needed).  What I am confused about is how come setting 48000/16bit which will in turn change to 44100/16bit if the game demands it ends up with clearer audio.  I think it's something other than sample rate.  Maybe it has to do with wfm.nAvgBytesPerSec ?

>Also, with my sound set to 24bit
That's a bad idea.  That's the source voice bitrate, not the mastering voice bitrate.  The source must always be set to what the audio data is unless I do the sample/bit conversion myself.  That last part is out of scope for me with this plugin.

**Comment by Frank-74** [comment] 2017-03-09 14:18
> That's a bad idea. That's the source voice bitrate, not the mastering voice bitrate.

No, I mean my soundcard's settings set to the default 24 bit.  If I restore defaults, it sets output to 24 bit 48000 Hz.  Which is when I have major stuttering issues with the new audiocode.  If I set my soundcard to 16 bit, there's hardly any stuttering.  Which is why I thought there should be a way to control the soundcard output, or cater for 24 bit which seems the default these days with Windows 8.1+ and cheap crappy onboard audio.

Otherwise, people will have to change their audio settings to 16 bit 44100 in Windows to use the plugin without problems.

**Comment by Frank-74** [comment] 2017-03-09 14:30
Here's the build I'm using.  It might have something to do with removing the win32 plugin hack, that calls main twice.  I remember this causing confusion a couple of years ago, about a mystery thread being created by PJ64 on Emutalk, which is why I removed the hack.
Just the .exe, I'm using default plugins, settings etc.
https://www.dropbox.com/s/4gq84yq7d4vsap3/Project64_Frank.zip?dl=1

**Comment by Azimer** [comment] 2017-03-09 15:05
Can you list out your plugins?  I dropped your exe in the folder (after appending _Frank.exe to it) and it worked without any issues.  I don't suspect it's the plugin hack causing the problem... it has to be another plugin we are using that's different.

**Comment by Frank-74** [comment] 2017-03-09 15:54
Here's my plugin folder with needed dll's in .exe folder.  But I'm only using default plugins except for AziAudio plugins.  I use Jabo's 1.6.1 for Goldeneye.

TWINE I use all default plugins, default Jabo's 1.7, default RSP, default PJNRage.  And AziAudio 0.7.  I built all backends, and renamed them, so I could see which was what when selecting them in PJ64.

https://www.dropbox.com/s/pr6yqzud1o4nf0t/Project64plugins.zip?dl=1

**Comment by Frank-74** [comment] 2017-03-09 16:09
>  I think it's something other than sample rate. Maybe it has to do with wfm.nAvgBytesPerSec ?

I think it's to do with this, when the windows sound setting is 24 bit:
wfm.wBitsPerSample = 16;

wfm.nAvgBytesPerSec = wfm.nSamplesPerSec * (wfm.wBitsPerSample / 8 * wfm.nChannels)

**Comment by Azimer** [comment] 2017-03-09 17:33
I am unlikely to change anything for the wfm settings.  I did some silly things like setting nSamplesPerSec to 8192 and I didn't hear any difference.  I think SetSampleRate may be recalculating this value?  It's just weird you get better quality with 48000 vs 44100 and I get no difference in quality or performance from 44100 vs 8192.  This makes sense when you know the sample rate is being changed by the SetSampleRate command on frequency change... but your scenario is making less sense.

So when you set buffer to 4x but leave Frequency at 44100, do you still receive poor audio quality?  How bad is that quality?  Is setting 4x or 48000 more significant for improved quality?  I am wondering if it's better to round the Frequency values on AI_SetFrequency rather than continue down the 48000 path.  I can change the frank branch and see if it does anything...  I believe the API automatically matches it to set frequencies.

**Comment by LegendOfDragoon** [comment] 2017-03-09 17:40
I use 48000 for wfm.nSamplesPerSec simply because Pokemon Stadium 2 GB Tower uses 48009 :smile: . I don't recall hearing much of a difference though.

I don't seem to notice a difference between setting it to 24 or 16 bit in windows sound setting. I think I will stick with 16, as I originally did, after tweaking sound settings a while back.

**Comment by Azimer** [comment] 2017-03-09 17:50
```C++
	Frequency = video_clock / (Dacrate + 1);
	if ((Frequency > 7000) && (Frequency < 9000))
		Frequency = 8000;
	else if ((Frequency > 10000) && (Frequency < 12000))
		Frequency = 11025;
	else if ((Frequency > 21000) && (Frequency < 23000))
		Frequency = 22050;
	else if ((Frequency > 31000) && (Frequency < 33000))
		Frequency = 32000;
	else if ((Frequency > 43000) && (Frequency < 45000))
		Frequency = 44100;
	else if ((Frequency > 47000) && (Frequency < 49000))
		Frequency = 48000;
```

We could round the frequencies like this if it would help at all.  I really don't think so but I also see no harm.  48000 put in nSamplesPerSec should be overwritten by AiDacreateChanged effectively unless you mean the PrimaryBuffer / MasteringVoice ?  This is what I can't wrap my head around.  I wish so much I could reproduce this, but both my Win8 laptop and my Win7 beast machine both play the audio consistently well in TWINE.

**Comment by Azimer** [comment] 2017-03-09 18:36
Still no dice frank.  Except I noticed the audio isn't loading the default sound volume.  My hears :(

**Comment by oddMLan** [comment] 2017-03-09 18:46
Maybe @Frank-74 you could post audio snippets to see if we are able to hear the difference? It might just be the sound sounds brighter due to the higher frequency. I got a good pair of cans now : 3

As well link me to a normal build and a modified build with the 48000Hz setting so I can check for myself and report back any difference

**Comment by Azimer** [comment] 2017-03-09 19:41
@Frank-74 I created a Youtube video of my testing.  https://youtu.be/qVagKZGeyc4

**Comment by Frank-74** [comment] 2017-03-09 21:03
I fell asleep....

Hmmm, I get instant crash with DS8, all I do is end emulation, double click game to restart, don't touch the settings.  Drivers problem I suppose, if no one else can reproduce.  DS8 sounds clearer/fuller compared to XA2.

Saved audio volume loads ok here.

When I set to 4x buffer, sound is ok with 24bit soundcard setting.
Set to 2x buffer, sound is stuttery as hell in TWINE/Resident Evil 2 with soundcard set to 24 bit.  Goldeneye is good though.
Set to 2x buffer with soundcard set to 16 bit 44100/48000, sound is ok.  Slight stutters.

I'll rebuild with latest master and test again.  Later tonight.  Seems only musyx games are problem though.

I guess it's a problem with this crappy Realtek High Definition Audio.  If the maxbuffersize can be configured from the options, I can just set it to 4x and get good sound.  I found increasing the maxbuffer to 5x, and I start getting static crackling.  Odd values not a multiple of 4/8 seem to cause static crackles here.

**Comment by Azimer** [comment] 2017-03-09 21:21
Yeah I get some odd static crackles too...  specifically at 60 with musyx.  This is likely due to the game overwriting the audio with new frames before the audio plugin reads it.  If you consider a double buffer scenario... if you haven't read the first buffer before it begins writing the third (overwriting the first) you'll end up with crackles.

**Comment by Frank-74** [comment] 2017-03-09 21:46
Monaco Grand Prix (U) crackles bad as well.  Though I think it's caused by gfx struggling using PJGlide.  Especially on the grid before race start, when it's drawing lots of cars.

**Comment by Azimer** [comment] 2017-03-09 22:40
I think so too Frank.  I wonder how much if your trouble is resource fighting.  It's hard to know for sure without a dummy graphics plugin.  I ran Monaco using your build / plugins and one using my build / plugin.  It sounds fine here.  https://youtu.be/MTOF2aswAXY .

**Comment by Frank-74** [comment] 2017-03-09 22:50
I'm just about to test my builds on a cheap Windows 8.1 tablet (£50 brand new).  It has Intel SST Audio Device (WDM).  No sample rate options available, only 16bit 48000, but it does have hardware acceleration option, that this laptop doesn't have.  Just installing dropbox on it, and downloading my dropbox, will take a while.

I wonder if the problem is my laptop's audio has no hardware acceleration, and does all the samplerate conversions etc. in software, causing the stuttering/bad audio.

**Comment by Frank-74** [comment] 2017-03-09 23:19
Hmmmm, no problems on 1.4Ghz dual core tablet.  DS8 doesn't crash either.  The only error I'm getting is missing XINPUT1_3.dll.  But NRage still works anyway.

Also, turning off hardware acceleration it's ok too.

Performance is better on the tablet with Intel SST Audio.  It's Realtek sound that's the problem.  I'll try some different drivers, see if that helps.

**Comment by Frank-74** [comment] 2017-03-10 00:53
Fixed! :)

Slightly newer HP drivers, no more crashing with DS8.  And I rebuilt XA2/DS8 with default 44100 and freq / 90 * 4 * 2.  Doesn't stutter bad now either, only slightly.  Windows sound settings are on default 24 bit, 48000.  Success... :rofl: 

TWINE and RE2 are still better with larger buffer though.  Do those games use 120 audio frame rate?

**Comment by Azimer** [comment] 2017-03-10 01:13
Awesome.  This issue has gotten very long and we have a resolution.  I am going to close it.  Please open a new issue for anything else.  I am not sure exactly which ones use 120 fps but musyx games are the worst.  I think Gauntlet Legends is one of them.

**Closed by Azimer** 2017-03-10 01:13 UTC
Labels: fixed
