### ISSUE TITLE
Savestateproblem in PJ64 with Azimers Soundplugin

### ISSUE THREAD

**Issue by GuTREwE** [Azimer/AziAudio#107] opened 2015-06-24 12:53 UTC
Hi,

I want to report one bug
If I have choosen Azimer Sound Plugin(v0.7wip5) in PJ64 and I loading any savestate than it crash with following errormessage
Unknown memory action
Emulation stopped

And it happens not with other soundplugins and previous versions

https://github.com/project64/project64/issues/515

**Comment by Azimer** [comment] 2015-06-24 19:28
This is a big of a known issue.  It's good to put it in issue tracker, especially with a link referring to the Project64 issue as well.

**Comment by cxd4** [comment] 2015-08-19 15:26
Haven't really been reading much about this issue since I rarely encounter it...I did just make saved states with latest AziAudio HLE and LLE, and tried loading them both in Mario64 and alternating them.  I seem to understand nothing fundamental about this issue, so what's a normal way to reproduce it?

Do we already know when the regression happened?

**Comment by Azimer** [comment] 2015-08-21 18:20
I don't really think it's a regression but a bug that's always existed in some form.  It seems to be worse with the 2.x versions of PJ64 compared to 1.6.  I plan to make a testing pass on this prior to making public 0.70 (non-WIP).

**Comment by AmbientMalice** [comment] 2015-08-23 01:25
The Xaudio2 version loads save states without crashing, but the audio is gone. I think the key think to look at would be why soft-resetting the emulator with F1 stops the crashes/muting.

**Comment by Frank-74** [comment] 2017-02-07 21:55
Should be fixed now.

**Comment by Azimer** [comment] 2017-02-28 14:50
I am working on some fixes for the new audio code with save states.  Once I fix up DirectSound, I will mark this completed and closed.

**Closed** 2017-03-07 20:50 UTC
Labels: bug, fixed
