### ISSUE TITLE
AeroFighters Most annoying sound ever!!!

### ISSUE THREAD

**Issue by theboy181** [Azimer/AziAudio#43] opened 2015-05-07 20:29 UTC
Just wondered why this game has to kill me ears with this plugin?

**Comment by LegendOfDragoon** [comment] 2015-05-07 20:50
same issue as #6

**Comment by theboy181** [comment] 2015-05-23 04:59
fixed!!! YAY!!

**Comment by Azimer** [comment] 2015-05-23 05:17
There is still quite a bit of static in the background I do not hear in LLE RSP.  I will need to investigate further.

**Comment by theboy181** [comment] 2015-05-23 05:18
Ill reopen then.. but the most annoying noise is not present.. ;)

**Comment by Azimer** [comment] 2015-05-23 05:35
Also to note... we have a "regression" in Golden Eye with the Nintendo logo.  Seems to be related to the filter.  I wonder if m64p has this issue too since I basically ported his code nearly exactly.  I will have to double check my interpretation and then have to go to a dump of IMEM.

**Comment by bsmiles32** [comment] 2015-05-23 12:57
@Azimer: FYI, goldeneye uses a different envmixer command than the "exponential" envmixer found in ABI1 games. Take a look at alist_envmix_ge in my sources (https://github.com/mupen64plus/mupen64plus-rsp-hle/blob/master/src/alist.c#L360). That should fix many "missing" sounds in goldeneye (very noticeable during the intro, the surface or cavern levels).
However, since I doubt that aerofighters uses the same ucode as goldeneye, the issue you're having here lies elsewhere.

**Comment by Azimer** [comment] 2015-05-23 13:43
@bsmiles32 : I know this issue is in my translation of POLEF.  My setting the L1/L2 variables to 0 on resume, I can remove the static.  I am thinking it's an endianess issue.  I am aware of the GoldenEye envmixer issue.  I notice the golden eye missing sound most notably on the first Dam level where you never get the bells playing.

Thanks again for all your hard work you've put into the audio microcode over the last couple years.  A testament to when open source works and why I will open source everything I do going forward.  Who knows where audio hle would be today if I never distributed source in the first place.

**Comment by theboy181** [comment] 2015-05-23 15:53
Slow clap!!

**Comment by cxd4** [comment] 2015-05-23 16:09
It's a pretty overestimated thing open-source, but also a pretty underestimated thing.

**Comment by LegendOfDragoon** [comment] 2015-05-23 17:57
@Azimer & @bsmiles32 , Body Harvest has the same ucode as Aero Fighters. I mentioned an issue with Body Harvest in #20. I think it might be related.

**Comment by Azimer** [comment] 2015-05-26 02:59
@theboy181 : This issue is resolved in the latest commit.
@LegendOfDragoon : If Body Harvest is still broken, please submit a new issue.  Aero Fighters is no longer broken.  Thanks!

**Closed by Azimer** 2015-05-26 02:59 UTC

**Comment by LegendOfDragoon** [comment] 2015-05-26 22:56
I tested Body Harvest and the issue now seems to be fixed :smile: .
